#!/usr/bin/env bash
# Regenerate the string table in docs/UI-CONTRACT.md from the doc comments in
# Sources/BranchBarCore/Strings.swift, so the document a reviewer reads and the code the app runs
# cannot drift. PLAN.md §3: "Strings are code."
#
# Convention every public member in Strings.swift follows:
#
#     /// State: `<state id>` — why the user is here.
#     /// Literal: `<what they read>`
#     public static let member = "…"
#
# Both lines may wrap across further `///` lines; wrapped lines are joined with a space. Members
# are emitted in source order, grouped by the enclosing `// MARK: -` heading. Running this twice
# changes nothing.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="$ROOT/Sources/BranchBarCore/Strings.swift"
DOC="$ROOT/docs/UI-CONTRACT.md"
BEGIN_MARKER='<!-- BEGIN doc-strings: generated by scripts/doc-strings.sh; edit Strings.swift, not this table -->'
END_MARKER='<!-- END doc-strings -->'

[ -f "$SOURCE" ] || { echo "doc-strings: missing $SOURCE" >&2; exit 1; }
[ -f "$DOC" ] || { echo "doc-strings: missing $DOC" >&2; exit 1; }
grep -qF "$BEGIN_MARKER" "$DOC" || { echo "doc-strings: $DOC has no BEGIN marker" >&2; exit 1; }
grep -qF "$END_MARKER" "$DOC" || { echo "doc-strings: $DOC has no END marker" >&2; exit 1; }

TABLE="$(mktemp)"
OUT="$(mktemp)"
trap 'rm -f "$TABLE" "$OUT"' EXIT

awk '
function flush() { state = ""; literal = ""; mode = "" }
BEGIN { flush(); group = "—"; print "| Group | Member | State it serves | Literal |"; print "|---|---|---|---|" }

/^[[:space:]]*\/\/ MARK: - / {
    line = $0
    sub(/^[[:space:]]*\/\/ MARK: - /, "", line)
    group = line
    next
}
/^[[:space:]]*\/\/\/ State: / {
    line = $0
    sub(/^[[:space:]]*\/\/\/ State: /, "", line)
    state = line
    mode = "state"
    next
}
/^[[:space:]]*\/\/\/ Literal: / {
    line = $0
    sub(/^[[:space:]]*\/\/\/ Literal: /, "", line)
    literal = line
    mode = "literal"
    next
}
/^[[:space:]]*\/\/\// {
    line = $0
    sub(/^[[:space:]]*\/\/\/[[:space:]]?/, "", line)
    if (mode == "state") state = state " " line
    else if (mode == "literal") literal = literal " " line
    next
}
/^[[:space:]]*public static (let|var|func) / {
    line = $0
    sub(/^[[:space:]]*public static (let|var|func)[[:space:]]+/, "", line)
    name = line
    sub(/[^A-Za-z0-9_].*$/, "", name)
    if (state == "") state = "—"
    if (literal == "") literal = "—"
    printf "| %s | `%s` | %s | %s |\n", group, name, state, literal
    flush()
    next
}
{ flush() }
' "$SOURCE" > "$TABLE"

awk -v begin_marker="$BEGIN_MARKER" -v end_marker="$END_MARKER" -v table="$TABLE" '
BEGIN { while ((getline row < table) > 0) rows = rows row "\n" }
$0 == begin_marker { print; printf "%s", rows; inside = 1; next }
$0 == end_marker { inside = 0; print; next }
!inside { print }
' "$DOC" > "$OUT"

if cmp -s "$OUT" "$DOC"; then
    echo "doc-strings: docs/UI-CONTRACT.md already up to date ($(( $(wc -l < "$TABLE") - 2 )) strings)"
else
    cat "$OUT" > "$DOC"
    echo "doc-strings: rewrote the string table in docs/UI-CONTRACT.md ($(( $(wc -l < "$TABLE") - 2 )) strings)"
fi
